export const PERMISSIONS = {
  CUSTOMER_READ: 'customer:read',
  CUSTOMER_WRITE: 'customer:write',
  CUSTOMER_DELETE: 'customer:delete',

  CONTACT_READ: 'contact:read',
  CONTACT_WRITE: 'contact:write',

  LEAD_READ: 'lead:read',
  LEAD_WRITE: 'lead:write',

  OPPORTUNITY_READ: 'opportunity:read',
  OPPORTUNITY_WRITE: 'opportunity:write',

  QUOTATION_READ: 'quotation:read',
  QUOTATION_WRITE: 'quotation:write',
  QUOTATION_APPROVE: 'quotation:approve',

  CONTRACT_READ: 'contract:read',
  CONTRACT_WRITE: 'contract:write',
  CONTRACT_APPROVE_LEGAL: 'contract:approve:legal',
  CONTRACT_APPROVE_FINANCE: 'contract:approve:finance',
  CONTRACT_APPROVE_EXEC: 'contract:approve:executive',

  COMPETITOR_READ: 'competitor:read',
  COMPETITOR_WRITE: 'competitor:write',

  AUDIT_READ: 'audit:read',
  USER_MANAGE: 'user:manage',
} as const

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]

const ALL: Permission[] = Object.values(PERMISSIONS)

export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  admin: ALL,

  sales_manager: [
    PERMISSIONS.CUSTOMER_READ, PERMISSIONS.CUSTOMER_WRITE, PERMISSIONS.CUSTOMER_DELETE,
    PERMISSIONS.CONTACT_READ, PERMISSIONS.CONTACT_WRITE,
    PERMISSIONS.LEAD_READ, PERMISSIONS.LEAD_WRITE,
    PERMISSIONS.OPPORTUNITY_READ, PERMISSIONS.OPPORTUNITY_WRITE,
    PERMISSIONS.QUOTATION_READ, PERMISSIONS.QUOTATION_WRITE, PERMISSIONS.QUOTATION_APPROVE,
    PERMISSIONS.CONTRACT_READ, PERMISSIONS.CONTRACT_WRITE,
    PERMISSIONS.COMPETITOR_READ, PERMISSIONS.COMPETITOR_WRITE,
    PERMISSIONS.AUDIT_READ,
  ],

  sales_rep: [
    PERMISSIONS.CUSTOMER_READ, PERMISSIONS.CUSTOMER_WRITE,
    PERMISSIONS.CONTACT_READ, PERMISSIONS.CONTACT_WRITE,
    PERMISSIONS.LEAD_READ, PERMISSIONS.LEAD_WRITE,
    PERMISSIONS.OPPORTUNITY_READ, PERMISSIONS.OPPORTUNITY_WRITE,
    PERMISSIONS.QUOTATION_READ, PERMISSIONS.QUOTATION_WRITE,
    PERMISSIONS.CONTRACT_READ,
    PERMISSIONS.COMPETITOR_READ, PERMISSIONS.COMPETITOR_WRITE,
  ],

  legal: [
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.CONTRACT_READ, PERMISSIONS.CONTRACT_APPROVE_LEGAL,
  ],

  finance: [
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.CONTRACT_READ, PERMISSIONS.CONTRACT_APPROVE_FINANCE,
    PERMISSIONS.QUOTATION_READ, PERMISSIONS.QUOTATION_APPROVE,
  ],

  auditor: [
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.CONTACT_READ,
    PERMISSIONS.LEAD_READ,
    PERMISSIONS.OPPORTUNITY_READ,
    PERMISSIONS.QUOTATION_READ,
    PERMISSIONS.CONTRACT_READ,
    PERMISSIONS.COMPETITOR_READ,
    PERMISSIONS.AUDIT_READ,
  ],
}

export function permissionsFor(role: string): Permission[] {
  return ROLE_PERMISSIONS[role] ?? []
}
